name: CI/CD Pipeline

on:
  push:
    paths:
     - 'EndSem-WS3/**'
    branches: [ "main" ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install Backend Dependencies
        run: |
          cd EndSem-WS3/backend
          pip install -r requirements.txt
          # Add your test command here, e.g., pytest
      
   
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install Frontend Dependencies
        run: |
          cd EndSem-WS3/frontend
          npm install
          npm run build

      
      - name: Build with Docker Compose
        run: docker compose build